apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Sync Public Action Versions

on:
  push:
    branches:
      - test

permissions:
  scm-token-own: read

jobs:
  sync-action-versions:
    if: ${{ cloudbees.scm.branch == 'master' }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v2
        with:
          fetch-depth: 2

      - name: Check if action_artifacts.json changed
        id: check-changes
        uses: docker://alpine/git:latest
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "versioning/action_artifacts.json"; then
            echo -n "true" > $CLOUDBEES_OUTPUTS/result
          else
            echo -n "false" > $CLOUDBEES_OUTPUTS/result
          fi

      - name: Sync action versions to public repos
        id: sync-actions
        if: ${{ steps.check-changes.outputs.result == 'true' }}
        uses: ./actions/sync-public-action-versions
        with:
          app-id: ${{ vars.cloudbees_platform_app_id }}
          calculi-corp-installation-id: 103828310
          cloudbees-io-installation-id: ${{ vars.cloudbees_io_installation_id }}
          cloudbees-io-gha-installation-id: ${{ vars.cloudbees_io_gha_installation_id }}
          private-key-b64: ${{ secrets.cloudbees_platform_gh_app_key_b64 }}
          jira-api-token: "test"
      - name: Publish workflow evidence
        if: ${{ steps.check-changes.outputs.result == 'true' }}
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: ${{ steps.sync-actions.outputs.evidence-report }}
